#!/bin/bash

# Locate ourselves
self=$(readlink -f "${BASH_SOURCE[0]}")
scriptsdir=$(dirname ${self})
topdir=$(cd ${scriptsdir}/.. && pwd)

# Read settings
source ${topdir}/grapes.conf

# Conf file for multistrap
conf=$(mktemp)

# Get package list
packages=$(echo ${bootstrap_packages})

cat >${conf} <<EOF
[General]
unpack=true
bootstrap=Debian
aptsources=Debian

[Debian]
packages=${packages}
source=http://ftp.debian.org/debian
keyring=debian-archive-keyring
suite=${baseline}
EOF

sudo multistrap -a ${arch} -d ${builddir} -f ${conf}	\
&& sudo cp -a /etc/resolv.conf ${builddir}/etc/
result=${?}
rm -f ${conf}

if [ ${result} -eq 0 ]; then
   sudo mkdir -p ${builddir}/build ${builddir}/packages ${builddir}/opt/grapes
   result=${?}
fi

if [ ${result} -eq 0 ]; then
   uid=$(id -u)
   gid=$(id -g)
   sudo chown ${uid}:${gid}		\
           ${builddir}/opt/grapes	\
   && sudo chroot ${builddir} groupadd	\
	   --gid ${gid}	grapes		\
   && sudo chroot ${builddir} adduser	\
	   --disabled-password		\
	   --gecos ""			\
	   --home /opt/grapes		\
	   --no-create-home 		\
	   --uid ${uid} --gid ${gid}	\
	   grapes
   result=${?}
fi

if [ ${result} -eq 0 ]; then
   echo "grapes ALL = NOPASSWD:	ALL" >${conf}
   sudo cp ${conf} ${builddir}/etc/sudoers.d/grapes
   result=${?}
fi

exit ${result}
